//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarReport
    {
        public int id { get; set; }
        public string Information { get; set; }
        public string Libelle { get; set; }
        public int Id_Booking { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
