//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasswordResetToken
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string token { get; set; }
        public int user_id { get; set; }
    
        public virtual User User { get; set; }
    }
}
