//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopOver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StopOver()
        {
            this.StopOverAddress = new HashSet<StopOverAddress>();
        }
    
        public int Id { get; set; }
        public System.DateTime Departure_Date { get; set; }
        public System.DateTime Arrival_Date { get; set; }
        public int Id_Booking { get; set; }
        public int Id_Stop_Over_Type { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual StopOverType StopOverType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StopOverAddress> StopOverAddress { get; set; }
    }
}
