//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopOverAddress
    {
        public byte is_Departure { get; set; }
        public int Id_Stop_Over { get; set; }
        public int id_Address { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual StopOver StopOver { get; set; }
    }
}
