//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_address
    {
        public int id_user { get; set; }
        public int id_address { get; set; }
        public string address_Name { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual User User { get; set; }
    }
}
