//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRental.DAL
{
    using System;
    
    public partial class usp_Action_List_By_Role1_Result1
    {
        public string Libelle { get; set; }
        public int Id { get; set; }
        public int Id_Role { get; set; }
        public int Id_Action { get; set; }
        public int Id1 { get; set; }
        public string Libelle1 { get; set; }
    }
}
